name: "Publish Server Image"

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'apache/hugegraph'
      repository_branch:
        required: true
        default: 'docker'
      image_url:
        required: true
        default: 'hugegraph/hugegraph'
      tag:
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: ${{ inputs.image_url }}:${{ inputs.tag }}
    steps:
      - name: Reset env
        if: github.event_name == 'workflow_dispatch'
        run: |
         echo "repository_url=${{ inputs.repository_url }}" >> $GITHUB_ENV
         echo "repository_branch=${{ inputs.repository_branch }}" >> $GITHUB_ENV
         echo "image_url=$IMAGE_URI" >> $GITHUB_ENV
         echo "docker_registry_url=${{ inputs.docker_registry_url }}" >> $GITHUB_ENV
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.docker_registry_url }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_url }}
          ref: ${{ inputs.repository_branch }}
          fetch-depth: 2

      - name: Publish Docker images
        run: |
          pwd && ls -lh
          docker build -t $IMAGE_URI .
          docker images
          docker run -it $IMAGE_URI
          sleep 15s
          docker ps -a
          sleep 15s
          docker ps -a
          docker push $IMAGE_URI
          
