name: Validate Apache Release

on:
  workflow_dispatch:
    inputs:
      current_version:
        required: true
        default: '1.0.0'
      deploy_maven:
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRIPT_PATH: /.github/workflows/scripts
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # TODO: do we need svn & gpg environment?
      - name: Test Building Source & Running
        run: |
          bash $SCRIPT_PATH/validate-release.sh ${{ github.event.inputs.current_version }} ${{ matrix.JAVA_VERSION }}
      - name: Test Running Binary
        run: |
          echo "TODO: separate script to test binary"

    strategy:
      fail-fast: false
      matrix:
        JAVA_VERSION: [ '8', '11' ]
